//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_an_Winform
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuat
    {
        public string MaPX { get; set; }
        public string MaSP { get; set; }
        public int SoLuong { get; set; }
        public string MaNSX { get; set; }
    
        public virtual PhieuXuatHang PhieuXuatHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
